### ISSUE TITLE
Samples do not show how to persist Okuki history and hierarchies across Process death

### ISSUE THREAD

**Issue by Zhuinden** [wongcain/okuki#2]
The Okuki history should be parcelled and restored if a "snapshot" of it exists in the `savedInstanceState` bundle, but the samples do not have an example for this.

**Comment by Zhuinden** [comment]
https://media.giphy.com/media/G4iDgyVJnoXfy/giphy.gif

**Comment by wongcain** [comment]
Added to MVP Example. See [OkukiStateRestorer](https://github.com/wongcain/okuki/blob/master/okuki-toothpick-mvp-sample/src/main/java/okuki/sample/common/okuki/OkukiStateRestorer.java).
